// Code generated by ObjectBox; DO NOT EDIT.

package main

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(userBinding)
	model.RegisterBinding(productBinding)
	model.RegisterBinding(storeBinding)
	model.LastEntityId(3, 951846619275233843)
	model.LastIndexId(1, 7204456745477744477)

	return model
}
